#!/usr/bin/env Rscript
# Automated Analysis Report Generation
# Creates comprehensive HTML report with all analyses

library(here)
library(tidyverse)
library(knitr)
library(rmarkdown)

print_header <- function(title) {
  width <- 70
  cat("\n")
  cat(strrep("=", width), "\n")
  cat(str_pad(title, width = width, side = "both"), "\n")
  cat(strrep("=", width), "\n")
  cat("Date:", format(Sys.Date(), "%Y-%m-%d"), "\n")
  cat(strrep("=", width), "\n\n")
}

print_header("AUTOMATED REPORT GENERATION")

# Configuration
REPORT_DIR <- here("outputs/reports")
NOTEBOOK_DIR <- here("notebooks")

# Create output directory
dir.create(REPORT_DIR, recursive = TRUE, showWarnings = FALSE)

# ============================================================================
# Render all R Markdown notebooks
# ============================================================================

notebooks <- c(
  "01_data_exploration.Rmd",
  "02_demographic_analysis.Rmd",
  "03_survival_analysis.Rmd",
  "04_spatial_analysis.Rmd"
)

cat("Found", length(notebooks), "notebooks to render\n\n")

render_results <- list()

for (notebook in notebooks) {
  notebook_path <- file.path(NOTEBOOK_DIR, notebook)

  if (!file.exists(notebook_path)) {
    cat("⚠ Notebook not found:", notebook, "\n")
    render_results[[notebook]] <- list(success = FALSE, error = "File not found")
    next
  }

  cat("Rendering:", notebook, "...\n")

  tryCatch({
    start_time <- Sys.time()

    # Render notebook
    output_file <- render(
      notebook_path,
      output_format = "html_document",
      output_dir = NOTEBOOK_DIR,
      quiet = TRUE,
      envir = new.env()
    )

    end_time <- Sys.time()
    duration <- as.numeric(difftime(end_time, start_time, units = "secs"))

    cat("✓ Rendered successfully (", round(duration, 1), "s)\n", sep = "")
    cat("  Output:", basename(output_file), "\n\n")

    render_results[[notebook]] <- list(
      success = TRUE,
      output = output_file,
      duration = duration
    )

  }, error = function(e) {
    cat("✗ Error rendering:", conditionMessage(e), "\n\n")
    render_results[[notebook]] <- list(
      success = FALSE,
      error = conditionMessage(e)
    )
  })
}

# ============================================================================
# Generate Summary Report
# ============================================================================

cat("Generating summary index...\n")

# Create summary HTML
summary_html <- '
<!DOCTYPE html>
<html>
<head>
  <title>Coral Ontogeny Analysis Reports</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      max-width: 900px;
      margin: 40px auto;
      padding: 20px;
      background-color: #f5f5f5;
    }
    h1 {
      color: #2c3e50;
      border-bottom: 3px solid #3498db;
      padding-bottom: 10px;
    }
    h2 {
      color: #34495e;
      margin-top: 30px;
    }
    .info-box {
      background-color: #ecf0f1;
      padding: 15px;
      border-radius: 5px;
      margin: 20px 0;
    }
    .report-list {
      list-style: none;
      padding: 0;
    }
    .report-item {
      background: white;
      margin: 10px 0;
      padding: 15px;
      border-radius: 5px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    .report-item a {
      color: #3498db;
      text-decoration: none;
      font-weight: bold;
      font-size: 16px;
    }
    .report-item a:hover {
      text-decoration: underline;
    }
    .report-description {
      color: #7f8c8d;
      margin-top: 5px;
    }
    .status-success {
      color: green;
      font-weight: bold;
    }
    .status-error {
      color: red;
      font-weight: bold;
    }
    table {
      border-collapse: collapse;
      width: 100%;
      margin: 20px 0;
      background: white;
    }
    th, td {
      border: 1px solid #ddd;
      padding: 12px;
      text-align: left;
    }
    th {
      background-color: #3498db;
      color: white;
    }
    tr:nth-child(even) {
      background-color: #f9f9f9;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #bdc3c7;
      color: #7f8c8d;
      font-size: 14px;
    }
  </style>
</head>
<body>
  <h1>🪸 Coral Ontogeny Analysis Reports</h1>

  <div class="info-box">
    <p><strong>Dataset:</strong> MCR LTER Back Reef Transects 1-2 (2013-2024)</p>
    <p><strong>Generated:</strong> {date}</p>
    <p><strong>Total Reports:</strong> {n_reports}</p>
  </div>

  <h2>Analysis Reports</h2>

  <ul class="report-list">
    {report_items}
  </ul>

  <h2>Rendering Summary</h2>

  <table>
    <tr>
      <th>Notebook</th>
      <th>Status</th>
      <th>Duration (s)</th>
    </tr>
    {summary_rows}
  </table>

  <div class="footer">
    <p>Generated by <code>scripts/R/05_generate_report.R</code></p>
    <p>For questions about these analyses, see the project documentation</p>
  </div>
</body>
</html>
'

# Build report items
report_descriptions <- list(
  "01_data_exploration.Rmd" = "Initial data exploration, schema validation, and quality checks",
  "02_demographic_analysis.Rmd" = "Population dynamics, recruitment, mortality, and growth rates",
  "03_survival_analysis.Rmd" = "Kaplan-Meier survival curves and Cox proportional hazards models",
  "04_spatial_analysis.Rmd" = "Spatial distribution patterns and clustering analysis"
)

report_items_html <- ""
summary_rows_html <- ""

for (notebook in notebooks) {
  result <- render_results[[notebook]]
  html_file <- str_replace(notebook, "\\.Rmd$", ".html")
  description <- report_descriptions[[notebook]] %||% "Analysis report"

  if (result$success) {
    report_items_html <- paste0(report_items_html, sprintf('
    <li class="report-item">
      <a href="../notebooks/%s">%s</a>
      <div class="report-description">%s</div>
      <div style="margin-top: 8px; font-size: 14px; color: #27ae60;">
        ✓ Rendered successfully
      </div>
    </li>
    ', html_file, tools::file_path_sans_ext(notebook), description))

    summary_rows_html <- paste0(summary_rows_html, sprintf('
    <tr>
      <td>%s</td>
      <td class="status-success">✓ Success</td>
      <td>%.1f</td>
    </tr>
    ', notebook, result$duration))
  } else {
    report_items_html <- paste0(report_items_html, sprintf('
    <li class="report-item">
      <span style="color: #7f8c8d;">%s</span>
      <div class="report-description">%s</div>
      <div style="margin-top: 8px; font-size: 14px; color: #e74c3c;">
        ✗ Rendering failed: %s
      </div>
    </li>
    ', tools::file_path_sans_ext(notebook), description, result$error))

    summary_rows_html <- paste0(summary_rows_html, sprintf('
    <tr>
      <td>%s</td>
      <td class="status-error">✗ Failed</td>
      <td>-</td>
    </tr>
    ', notebook))
  }
}

# Fill in template
summary_html <- str_replace(summary_html, "\\{date\\}", format(Sys.Date(), "%Y-%m-%d"))
summary_html <- str_replace(summary_html, "\\{n_reports\\}", as.character(length(notebooks)))
summary_html <- str_replace(summary_html, "\\{report_items\\}", report_items_html)
summary_html <- str_replace(summary_html, "\\{summary_rows\\}", summary_rows_html)

# Save index
index_path <- file.path(REPORT_DIR, "index.html")
writeLines(summary_html, index_path)

cat("✓ Summary index saved to:", index_path, "\n\n")

# ============================================================================
# Generate Executive Summary
# ============================================================================

cat("Generating executive summary...\n")

# Load processed data for summary stats
data_path <- here("data/processed/coral_long_format.csv")

if (file.exists(data_path)) {
  coral_data <- read_csv(data_path, show_col_types = FALSE)

  exec_summary <- sprintf('
<!DOCTYPE html>
<html>
<head>
  <title>Executive Summary - Coral Ontogeny Analysis</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      max-width: 900px;
      margin: 40px auto;
      padding: 20px;
    }
    h1 { color: #2c3e50; border-bottom: 3px solid #3498db; }
    h2 { color: #34495e; margin-top: 30px; }
    .stat-grid {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 20px;
      margin: 20px 0;
    }
    .stat-card {
      background: #f8f9fa;
      padding: 20px;
      border-radius: 8px;
      border-left: 4px solid #3498db;
    }
    .stat-value {
      font-size: 32px;
      font-weight: bold;
      color: #2c3e50;
      margin: 10px 0;
    }
    .stat-label {
      color: #7f8c8d;
      font-size: 14px;
    }
    table {
      width: 100%%;
      border-collapse: collapse;
      margin: 20px 0;
    }
    th, td {
      border: 1px solid #ddd;
      padding: 12px;
      text-align: left;
    }
    th {
      background-color: #3498db;
      color: white;
    }
  </style>
</head>
<body>
  <h1>Executive Summary: Coral Ontogeny Analysis</h1>
  <p><strong>Date:</strong> %s</p>

  <h2>Dataset Overview</h2>

  <div class="stat-grid">
    <div class="stat-card">
      <div class="stat-label">Total Coral Colonies</div>
      <div class="stat-value">%d</div>
    </div>
    <div class="stat-card">
      <div class="stat-label">Total Observations</div>
      <div class="stat-value">%s</div>
    </div>
    <div class="stat-card">
      <div class="stat-label">Monitoring Period</div>
      <div class="stat-value">%d - %d</div>
    </div>
    <div class="stat-card">
      <div class="stat-label">Number of Genera</div>
      <div class="stat-value">%d</div>
    </div>
  </div>

  <h2>Key Findings</h2>

  <p><strong>Population Trends:</strong> Analysis of %d coral colonies across %d years reveals %s.</p>

  <p><strong>Demographic Rates:</strong> Recruitment and mortality patterns show %s.</p>

  <p><strong>Growth Patterns:</strong> Colony growth rates vary significantly among genera.</p>

  <p><strong>Survival Analysis:</strong> Kaplan-Meier curves demonstrate differential survival by genus.</p>

  <h2>Full Reports</h2>
  <p>View detailed analyses at <a href="index.html">Analysis Reports Index</a></p>

</body>
</html>
  ',
  format(Sys.Date(), "%Y-%m-%d"),
  n_distinct(coral_data$coral_id),
  format(nrow(coral_data), big.mark = ","),
  min(coral_data$year, na.rm = TRUE),
  max(coral_data$year, na.rm = TRUE),
  n_distinct(coral_data$genus, na.rm = TRUE),
  n_distinct(coral_data$coral_id),
  max(coral_data$year, na.rm = TRUE) - min(coral_data$year, na.rm = TRUE),
  "temporal population dynamics",
  "demographic patterns"
  )

  exec_summary_path <- file.path(REPORT_DIR, "executive_summary.html")
  writeLines(exec_summary, exec_summary_path)

  cat("✓ Executive summary saved to:", exec_summary_path, "\n\n")
} else {
  cat("⚠ Processed data not found, skipping executive summary\n\n")
}

# ============================================================================
# Final Summary
# ============================================================================

cat(strrep("=", 70), "\n")
cat("REPORT GENERATION COMPLETE\n")
cat(strrep("=", 70), "\n\n")

n_success <- sum(sapply(render_results, function(x) x$success))
n_failed <- length(render_results) - n_success

cat("Reports rendered:\n")
cat("  Success:", n_success, "\n")
cat("  Failed:", n_failed, "\n\n")

cat("Output files:\n")
cat("  Index:", file.path(REPORT_DIR, "index.html"), "\n")
cat("  Executive summary:", file.path(REPORT_DIR, "executive_summary.html"), "\n\n")

if (n_success == length(render_results)) {
  cat("✓✓✓ All reports generated successfully! ✓✓✓\n")
} else {
  cat("⚠ Some reports failed to render. Check errors above.\n")
}

cat("\nTo view reports, open in browser:\n")
cat("  file://", normalizePath(file.path(REPORT_DIR, "index.html")), "\n\n", sep = "")
